version: '3.9'
services:
  api:
    build:
      dockerfile: Dockerfile.nest
      context: .
      # Only will build development stage from our dockerfile
      target: development
    container_name: nestjs-api
    volumes:
      - ./nest-api:/usr/src/app
      - ./nest-api/node_modules:/usr/src/app/node_modules
    # Run a command against the development stage of the image
    command: npm run start:dev
    ports:
      - 3000:3000
    networks:
      - server-network
    depends_on:
      - postgres-service
  postgres-service:
    container_name: postgres
    image: postgres:14.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - server-network
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:5.5
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    networks:
      - server-network
    depends_on:
      - postgres-service
networks:
  server-network:




